apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: jollykyles/weather-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: BASE_URL
          value: "https://api.open-meteo.com/v1/forecast"
